/// Generated by AssetsRefGenerator on ????/??/??
class Res {
  static const String m = "assets/images/m.jpg";
  static const String n = "assets/images/n.jpg";
  static const String s = "assets/images/s.jpg";
}
